backend:
    name: git-gateway
    branch: 'main'
media_folder: 'public/images/uploads'
public_folder: '/images/uploads'
collections:
    - name: 'blog'
      label: 'Blog'
      folder: 'content/blog'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      extension: 'md'
      format: 'yaml-frontmatter'
      sortable_fields:
          - publishedDate
          - title
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
                label: 'Published Date',
                name: 'publishedDate',
                widget: 'datetime',
                required: false,
            }
          - {
                label: 'Featured Image',
                name: 'image',
                widget: 'image',
                required: false,
            }
          - {
                label: 'Description',
                name: 'description',
                widget: 'text',
                required: false,
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
    - name: 'talks'
      label: 'Talks'
      folder: 'content/talks'
      create: true
      slug: '{{slug}}'
      extension: 'md'
      format: 'yaml-frontmatter'
      sortable_fields:
          - publishedDate
          - title
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
          - {
                label: 'Published Date',
                name: 'publishedDate',
                widget: 'datetime',
                required: false,
            }
          - {
                label: 'Description',
                name: 'description',
                widget: 'text',
                required: false,
            }
    - name: 'projects'
      label: 'Projects'
      folder: 'content/projects'
      create: true
      slug: '{{slug}}'
      extension: 'md'
      format: 'yaml-frontmatter'
      sortable_fields:
          - publishedDate
          - title
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
                label: 'Published Date',
                name: 'publishedDate',
                widget: 'datetime',
                required: false,
            }
          - {
                label: 'Featured Image',
                name: 'image',
                widget: 'image',
                required: false,
            }
          - { label: 'Description', name: 'description', widget: 'string' }
          - label: 'Links'
            name: 'links'
            widget: list
            fields:
                - { label: 'Title', name: 'title', widget: 'string' }
                - { label: 'URL', name: 'url', widget: 'string' }
